config/routes.rb
Rails.application.routes.draw do
  resources :levels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "tasks#index"

  resources :tasks

  put 'complete_task', to: 'tasks#complete', as: :complete_tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/level.rb
class Level < ApplicationRecord

  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :level

  scope :incomplete, -> { where(check: 0) }
  scope :complete, -> { where(check: 1) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:name, :weight)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @incomplete_tasks = Task.incomplete
    @complete_tasks = Task.complete
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(post_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(post_params)
    redirect_to tasks_path
  end

  def complete
    Task.where(id: params[:task_ids]).update_all(check: true)
    redirect_to tasks_path
  end

  private

  def post_params
    params.require(:task).permit(:name, :details, :limit, :level_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetDaishi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="<%= new_task_path %>">Créer une nouvelle tâche</a></li>
          <li><a href="<%= tasks_path %>">Tâche</a></li>
          <li><a href="<%= levels_path %>">Niveau d'importance</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
  <div style="padding: 5%;">
    <%= yield %>
  </div>
  </body>
</html>

app/views/levels/_form.html.erb
<%= form_for(level) do |f| %>
  <% if level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing Level</h1>

<%= render 'form', level: @level %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.name %></td>
        <td><%= level.weight %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<h1>New Level</h1>

<%= render 'form', level: @level %>

<%= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @level.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @level.weight %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>

app/views/tasks/_form.html.erb
<%= form_for item do |t| %>
    <label>Nom de la tâche</label>
    <%= t.text_field :name,class: "form-control" %>
    <label>Detail de la tâche</label>
    <%= t.text_area :details,class: "form-control" %>
    <label>Date Limite de la tâche</label>
    <%= t.date_field :limit, min: Date.today, class: "form-control" %>
    <label>Niveau d'importante de la tâche</label>
    <%= t.collection_select :level_id, Level.all, :id, :name, {}, {} %>
    <br>
    <%= t.submit nil, class: 'btn btn-primary' %>
<% end %>
<br>
<a href="<% tasks_path %>" class="btn btn-info">Revenir à la liste des tâches</a>

app/views/tasks/edit.html.erb
<h1>Modifier la tâche</h1>

<%= render 'form', item: @task %>

app/views/tasks/index.html.erb
<h1>Incomplete Tasks</h1>
<%= form_tag(complete_tasks_path, method: :put)  do %>
    <% for task in @incomplete_tasks %>
        <ul>
          <li>
            <%= check_box_tag 'task_ids[]', task.id %>
            <%= task.name %>
          </li>
        </ul>
    <% end %>
    <%= submit_tag 'Mark as Complete' %>
<% end %>

<h1>Complete Tasks</h1>
<ul>
  <% for task in @complete_tasks %>
      <li>
        <%= task.name %>
      </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Créer la nouvelle tâche</h1>

<%= render 'tasks/form', item: @task %>

app/views/tasks/show.html.erb
<h1>Nom de la tâche</h1>
<%= @task.name %>
<h2>Detail de la tâche</h2>
<%= @task.details %>
<h2>Date limite de la tâche</h2>
<%= @task.limit %>
<h2>Niveau d'importance de la tâche</h2>
<%= @task.level %>
<br>
<a href="<%= tasks_path %>">Revenir aux tâches</a>